version: "3"

vars:
  GO_MODULE: github.com/rebelopsio/duet
  BUILD_DIR: "{{.ROOT_DIR}}/dist"
  COVERAGE_DIR: "{{.ROOT_DIR}}/coverage"

tasks:
  default:
    cmds:
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -rf {{.COVERAGE_DIR}}

  ensure-lint:
    internal: true
    cmds:
      - |
        if ! command -v golangci-lint &> /dev/null; then
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        fi

  lint:
    desc: Run golangci-lint
    deps: [ensure-lint]
    cmds:
      - golangci-lint run --config=.golangci.yml

  test:
    desc: Run tests
    cmds:
      - mkdir -p {{.COVERAGE_DIR}}
      - go test -race -coverprofile={{.COVERAGE_DIR}}/coverage.out -covermode=atomic ./...

  build:
    desc: Build binary
    deps: [clean]
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/duet cmd/duet/main.go

  install-tools:
    desc: Install development tools
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/goreleaser/goreleaser@latest

  generate:
    desc: Run go generate
    cmds:
      - go generate ./...

  pre-commit:
    desc: Run pre-commit checks
    cmds:
      - task: generate
      - task: lint
      - task: test
