name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false

      # Install Task - Linux/macOS
      - name: Install Task (Unix)
        if: runner.os != 'Windows'
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          echo "$HOME/.bin" >> $GITHUB_PATH

      # Install Task - Windows
      - name: Install Task (Windows)
        if: runner.os == 'Windows'
        run: |
          iwr -useb https://taskfile.dev/install.ps1 | iex
          echo "$HOME/.bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config=.golangci.yml
          skip-cache: true
          install-mode: binary

      - name: Run tests
        run: task test
        shell: bash

  release:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          echo "$HOME/.bin" >> $GITHUB_PATH

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/github
          semantic-release

  goreleaser:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          echo "$HOME/.bin" >> $GITHUB_PATH

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
