name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install Task
        run: |
          curl -fsSL https://github.com/go-task/task/releases/download/v3.30.1/task_linux_amd64.tar.gz | \
            sudo tar -xz -C /usr/local/bin task && \
            sudo chmod +x /usr/local/bin/task
        if: runner.os == 'Linux'

      - name: Install Task
        run: |
          curl -fsSL https://github.com/go-task/task/releases/download/v3.30.1/task_darwin_amd64.tar.gz | \
            sudo tar -xz -C /usr/local/bin task && \
            sudo chmod +x /usr/local/bin/task
        if: runner.os == 'macOS'

      - name: Run tests
        run: task test
